package com.vortex.kernel.snapshot;

public enum CheckpointRecoveryFailureReason {
    NO_CHECKPOINT_AVAILABLE,
    CHECKPOINT_METADATA_MISSING,
    FULL_CHECKPOINT_MISSING,
    DELTA_CHECKPOINT_MISSING_BASE,
    DELTA_CHAIN_BROKEN,
    DELTA_PAYLOAD_MISSING,
    DELTA_PAYLOAD_INVALID,
    BASE_FULL_CHECKPOINT_MISSING
}
