package com.vortex.kernel.snapshot;

public enum CheckpointRecoveryFailureReason {
    NO_CHECKPOINT_AVAILABLE,
    CHECKPOINT_METADATA_MISSING,
    CHECKPOINT_METADATA_LOAD_FAILED,
    CHECKPOINT_STORAGE_READ_FAILED,
    CHECKPOINT_VERSION_MISMATCH,
    FULL_CHECKPOINT_MISSING,
    FULL_CHECKPOINT_PAYLOAD_INVALID,
    DELTA_CHECKPOINT_MISSING_BASE,
    DELTA_CHAIN_BROKEN,
    DELTA_PAYLOAD_MISSING,
    DELTA_PAYLOAD_INVALID,
    BASE_FULL_CHECKPOINT_MISSING,
    DELTA_STATE_APPLY_FAILED,
    WAL_STATE_APPLY_FAILED
}
